name: CI setup
description: Set up an environment to run CI commands.

runs:
  using: composite
  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ env.OTP_VERSION }}
        elixir-version: ${{ env.ELIXIR_VERSION }}
    - name: Restore deps and _build cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Get dependencies
      run: mix deps.get
    - name: Compile dependencies
      run: mix deps.compile
