# TODO
#   Find a decent workflow for this that ensures all checks pass before
#   deployment happens. Once things are steady, running on release creation
#   might be a good candidate.
name: Create, verify and publish a Docker image on ghcr.io
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: tag
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          load: true
          tags: ${{ steps.tag.outputs.tags }}
          labels: ${{ steps.tag.outputs.labels }}

      - name: Smoke test Docker image
        run: docker run --rm  ${{ steps.build.outputs.imageid }} ./bin/training_schedule version

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tags }}
          labels: ${{ steps.tag.outputs.labels }}
