name: CI
on: [push, pull_request]

env:
  ELIXIR_VERSION: 1.14.3
  OTP_VERSION: 25.3
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: compiler output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mix-setup
      - run: mix compile --all-warnings --warnings-as-errors

  format:
    name: formatting
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mix-setup
      - run: mix format --check-formatted

  compile-tests:
    name: compiler output including tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mix-setup
        with:
          cache-prefix: test
      - run: MIX_ENV=test mix compile --all-warnings --warnings-as-errors

  test:
    name: tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mix-setup
        with:
          cache-prefix: test
      - run: mix test

  dialyzer:
    name: typechecks
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mix-setup
        with:
          cache-prefix: dialyzer
      - run: mix dialyzer --format github

  # TODO: set this up once we verify which checks we want
  # credo:
  #   name: code style
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/mix-setup
  #     - run: mix credo --figure-out-options
